### ISSUE TITLE
The `StyleGuide` attribute fails when running Rubocop

### ISSUE THREAD

**Issue by mssola** [SUSE/style-guides#12]
When running Rubocop version 0.32, I get the following warning:
```
Warning: unrecognized parameter Style/EmptyLinesAroundBlockBody:StyleGuide found in /home/mssola/Projects/mssola/Portus/config/rubocop-suse.yml
```
Maybe the rationale for each cop should be added as a comment instead of this (apparently unrecognized) attribute ?

**Comment by cornelius** [comment]
I think it would be better to fix this in rubocop. I opened a pull request: https://github.com/bbatsov/rubocop/pull/2305

**Comment by mssola** [comment]
Agreed, thanks for taking care of this.

**Comment by cornelius** [comment]
Patch was accepted, so this should be solved with the next Rubocop release.
