### ISSUE TITLE
Do we want fail() instead of raise for calling an exception?

### ISSUE THREAD

**Issue by keberle94** [SUSE/style-guides#9]
Right now I get the message that I should use fail() instead of raise to call an exception. Do we want to keep that? Right now our code contains a lot of raise-calls.

**Comment by aduffeck** [comment]
I think the idea behind this check is to use `fail` for new error conditions (where the code actually failed) and `raise` for re-raising existing exceptions. While that sounds reasonable to me I think the semantic benefit is small and `fail` seems to be pretty uncommon to use, so I'd rather continue just using `raise` everywhere like before.

**Comment by mssola** [comment]
I agree with @aduffeck

**Comment by cornelius** [comment]
@aduffeck, @mssola Could one of you prepare a patch to the style guide clarifying this?

**Comment by aduffeck** [comment]
Will do.

**Comment by aduffeck** [comment]
@cornelius done
